Configurely.App/ViewModels/Workflow/WorkFlowViewModel.cs
using Configurely.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Configurely.App.ViewModels.Workflow
{
    public class WorkFlowViewModel
    {
        public int DepartmentId { get; set; }

        public string DepartmentName { get; set; }

        public List<Field> CurrentFields { get; set; }

        public List<Field> AvailableFields { get; set; }
    }
}

Configurely.App/Controllers/WorkflowController.cs
using Configurely.App.ViewModels.Workflow;
using Configurely.Entities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Configurely.App.Controllers
{
    public class WorkflowController : Controller
    {
        /// <summary>
        /// Action thats serves the view that lists all Departments
        /// </summary>
        public async Task<ActionResult> Index()
        {
            List<Department> oDepartment = null;

            using (var client = new HttpClient())
            {
                var uri = new Uri("http://localhost:51506/ConfigurelyService.svc/GetDepartments");

                var json = await client.GetStringAsync(uri);

                oDepartment = JsonConvert.DeserializeObject<List<Department>>(json);
            }

            return View(oDepartment);
        }

        /// <summary>
        /// Action thats serves the view that lists all Available and current Fields for a Department
        /// </summary>
        public async Task<ActionResult> Edit(int id)
        {
            Department oDepartment = null;
            List<Field> fieldList = null;
            WorkFlowViewModel vm = new WorkFlowViewModel();

            using (var client = new HttpClient())
            {
                var uri = new Uri("http://localhost:51506/ConfigurelyService.svc/GetDepartment/" + id);

                var json = await client.GetStringAsync(uri);

                oDepartment = JsonConvert.DeserializeObject<Department>(json);

                uri = new Uri("http://localhost:51506/ConfigurelyService.svc/GetFields");

                json = await client.GetStringAsync(uri);

                fieldList = JsonConvert.DeserializeObject<List<Field>>(json);

                vm.DepartmentId = oDepartment.ID;
                vm.DepartmentName = oDepartment.Name;
                vm.CurrentFields = oDepartment.Fields;

                vm.AvailableFields = fieldList.Where(p => vm.CurrentFields.All(p2 => p2.ID != p.ID)).ToList();
            }

            return View(vm);
        }

        /// <summary>
        /// Action thats Adds a new field to a Department
        /// </summary>
        public async Task<ActionResult> Add(int departmentId, int fieldId)
        {
            object oResult = null;

            Department oDepartment = new Department();
            oDepartment.ID = departmentId;
            oDepartment.Fields = new List<Field>() { new Field() { ID = fieldId } };

            using (var client = new HttpClient())
            {
                HttpResponseMessage response = new HttpResponseMessage();
                client.BaseAddress = new Uri("http://localhost:51506/ConfigurelyService.svc/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var serializer = new JavaScriptSerializer();
                var json = serializer.Serialize(oDepartment);
                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                oResult = await client.PostAsync("http://localhost:51506/ConfigurelyService.svc/AddDepartmentField", stringContent);
            }

            return RedirectToAction("Edit", new { id = departmentId });
        }

        /// <summary>
        /// Action thats deletes a new field from a Department
        /// </summary>
        public async Task<ActionResult> Delete(int departmentId, int fieldId)
        {
            object oResult = null;

            Department oDepartment = new Department();
            oDepartment.ID = departmentId;
            oDepartment.Fields = new List<Field>() { new Field() { ID = fieldId } };


            using (var client = new HttpClient())
            {
                HttpResponseMessage response = new HttpResponseMessage();
                client.BaseAddress = new Uri("http://localhost:51506/ConfigurelyService.svc/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var serializer = new JavaScriptSerializer();
                var json = serializer.Serialize(oDepartment);
                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                oResult = await client.PostAsync("http://localhost:51506/ConfigurelyService.svc/DeleteDepartmentField", stringContent);
            }

            return RedirectToAction("Edit", new { id = departmentId });
        }
    }
}

Configurely.App/Views/Workflow/Edit.cshtml
@model Configurely.App.ViewModels.Workflow.WorkFlowViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Manage Department WorkFlow</h2>

<p>
    Department Id - @Html.DisplayFor(model => model.DepartmentId)
</p>
<p>
    Department Name - @Html.DisplayFor(model => model.DepartmentName)
</p>
<div class="col-xs-6">
    <h2 class="sub-header">Current Department Fields</h2>
    <table class="table table-condensed">
        <tr>
            <th>Field Id</th>
            <th>Field Name</th>
            <th></th>
        </tr>
        @foreach (var item in Model.CurrentFields)
        {
            <tr>
                <td>@Html.DisplayFor(o => item.ID) </td>
                <td>@Html.DisplayFor(o => item.Name)</td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { departmentId = Model.DepartmentId, fieldId = item.ID })
                </td>
            </tr>
        }
    </table>
</div>
<div class="col-xs-6">
    <h2 class="sub-header">Available Fields</h2>
    <table class="table table-condensed">
        <tr>
            <th>Field Id</th>
            <th>Field Name</th>
            <th></th>
        </tr>
        @foreach (var item in Model.AvailableFields)
        {
            <tr>
                <td>@Html.DisplayFor(o => item.ID) </td>
                <td>@Html.DisplayFor(o => item.Name)</td>
                <td>
                    @Html.ActionLink("Add", "Add", new { departmentId = Model.DepartmentId, fieldId = item.ID })
                </td>
            </tr>
        }
    </table>
</div>

Configurely.App/Views/Workflow/Index.cshtml
@model IEnumerable<Configurely.Entities.Department>

@{
    ViewBag.Title = "Index";
}

<h2>Departments</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Workflow", new { id = item.ID }, null)
        </td>
    </tr>
}

</table>